name: build executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install yarn && yarn install
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ORv1
          path: out/make
          retention-days: 90
