name: build executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install yarn && yarn install
      - name: Build
        run: yarn build
      - name: make build directory
        run: mkdir build
      - name: build info
        run: echo "##Open Recorder v1_${{ steps.get_date.outputs.date }} - download the executable here" | Out-File -FilePath build/build.md
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/ORv1.exe
          retention-days: 365
